### ISSUE TITLE
Launch file or nodes to run?

### ISSUE THREAD

**Issue by y22ma** [hengli/vmav-ros-pkg#1]
Hey guys,

Is there anyway you could put out a description of what nodes should be launched for this package for sparse and dense slam purposes?

I can take this information and generate a pull request for launchfiles.

Thanks

**Comment by hengli** [comment]
This description is specific to any AscTec platform with a VRmagic D3 multi-camera system, and will not work on other platforms.

These are the nodes needed to run sparse SLAM:
pkg="asctec_hl_interface" type="hl_node"
pkg="vrmagic_device" type="vrmagic_device_node"
pkg="gcam_slam" type="gcam_slam_node"

There is no implementation for dense SLAM.

**Comment by y22ma** [comment]
Ah. I'm actually using a pair of IDS camera with this stack. Had to rip out the VR magic and asctec dependencies, but stereo_vo is working quite well now. Will try running gcam_slam_node with this setup.
